---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  log: true
  lint:
    name: ansible-lint
platforms:
  - name: instance
    image: centos:7
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
