---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: "virtualbox"
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  log: true
  lint:
    name: ansible-lint
platforms:
  - name: "trusty64"
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8080"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    config_options:
      synced_folder: true
    box: trusty64
    box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
    memory: 512
    cpus: 1
    provider_options:
      gui: false
    provider_override_args:
      - "vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"
    provision: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
